version: "3"
services:
  boilerplate_db:
    image: "postgres"
    container_name: "boilerplate"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lopun
      POSTGRES_PASSWORD: bpdbdb
      POSTGRES_DB: boilerplate
    volumes:
      - bp_data:/var/lib/postgresql/data
volumes:
  bp_data:
    driver: "local"
